language: c
script: cd apps/test_app/client && make

os: linux
dist: trusty
sudo: required

before_install:
  - export CC=gcc-4.8
  - export CXX=g++-4.8
  - wget https://download.01.org/intel-sgx/linux-1.7/sgx_linux_x64_sdk_1.7.100.36470.bin -O sgx_sdk.bin
  - chmod +x sgx_sdk.bin
  - echo yes | ./sgx_sdk.bin
  - source sgxsdk/environment
  - openssl ecparam -name prime256v1 -genkey -noout -out private_key.pem
  - export PRIVATE_KEY_PATH=$PWD/private_key.pem
  - wget http://download.zeromq.org/zeromq-4.1.2.tar.gz
  - tar -xvf zeromq-4.1.2.tar.gz
  - cd zeromq-4.1.2 && ./autogen.sh && ./configure --without-libsodium && make && sudo make install && cd ..
  - wget https://github.com/zeromq/czmq/releases/download/v4.0.2/czmq-4.0.2.tar.gz
  - tar -xvf czmq-4.0.2.tar.gz
  - cd czmq-4.0.2 && ./configure && make && sudo make install && cd ..
  - git clone https://github.com/redis/hiredis.git
  - cd hiredis && make && sudo make install && cd ..
  - sudo apt-get install libgflags-dev libsnappy-dev zlib1g-dev libbz2-dev liblz4-dev
  - wget https://github.com/facebook/rocksdb/archive/rocksdb-5.14.3.tar.gz -O rocksdb.tar.gz
  - mkdir -P rocksdb && tar -zxf rocksdb.tar.gz -C rocksdb --strip-components=1
  - cd rocksdb && make static_lib && make install && cd ..
