// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tx.proto

#ifndef PROTOBUF_tx_2eproto__INCLUDED
#define PROTOBUF_tx_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace cctx {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_tx_2eproto();
void protobuf_AssignDesc_tx_2eproto();
void protobuf_ShutdownFile_tx_2eproto();

class Transaction;

// ===================================================================

class Transaction : public ::google::protobuf::Message {
 public:
  Transaction();
  virtual ~Transaction();

  Transaction(const Transaction& from);

  inline Transaction& operator=(const Transaction& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Transaction& default_instance();

  void Swap(Transaction* other);

  // implements Message ----------------------------------------------

  Transaction* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Transaction& from);
  void MergeFrom(const Transaction& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint64 amount = 1;
  inline bool has_amount() const;
  inline void clear_amount();
  static const int kAmountFieldNumber = 1;
  inline ::google::protobuf::uint64 amount() const;
  inline void set_amount(::google::protobuf::uint64 value);

  // required uint64 gmr = 2;
  inline bool has_gmr() const;
  inline void clear_gmr();
  static const int kGmrFieldNumber = 2;
  inline ::google::protobuf::uint64 gmr() const;
  inline void set_gmr(::google::protobuf::uint64 value);

  // required uint64 timestamp = 3;
  inline bool has_timestamp() const;
  inline void clear_timestamp();
  static const int kTimestampFieldNumber = 3;
  inline ::google::protobuf::uint64 timestamp() const;
  inline void set_timestamp(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:cctx.Transaction)
 private:
  inline void set_has_amount();
  inline void clear_has_amount();
  inline void set_has_gmr();
  inline void clear_has_gmr();
  inline void set_has_timestamp();
  inline void clear_has_timestamp();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::uint64 amount_;
  ::google::protobuf::uint64 gmr_;
  ::google::protobuf::uint64 timestamp_;
  friend void  protobuf_AddDesc_tx_2eproto();
  friend void protobuf_AssignDesc_tx_2eproto();
  friend void protobuf_ShutdownFile_tx_2eproto();

  void InitAsDefaultInstance();
  static Transaction* default_instance_;
};
// ===================================================================


// ===================================================================

// Transaction

// required uint64 amount = 1;
inline bool Transaction::has_amount() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Transaction::set_has_amount() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Transaction::clear_has_amount() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Transaction::clear_amount() {
  amount_ = GOOGLE_ULONGLONG(0);
  clear_has_amount();
}
inline ::google::protobuf::uint64 Transaction::amount() const {
  // @@protoc_insertion_point(field_get:cctx.Transaction.amount)
  return amount_;
}
inline void Transaction::set_amount(::google::protobuf::uint64 value) {
  set_has_amount();
  amount_ = value;
  // @@protoc_insertion_point(field_set:cctx.Transaction.amount)
}

// required uint64 gmr = 2;
inline bool Transaction::has_gmr() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Transaction::set_has_gmr() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Transaction::clear_has_gmr() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Transaction::clear_gmr() {
  gmr_ = GOOGLE_ULONGLONG(0);
  clear_has_gmr();
}
inline ::google::protobuf::uint64 Transaction::gmr() const {
  // @@protoc_insertion_point(field_get:cctx.Transaction.gmr)
  return gmr_;
}
inline void Transaction::set_gmr(::google::protobuf::uint64 value) {
  set_has_gmr();
  gmr_ = value;
  // @@protoc_insertion_point(field_set:cctx.Transaction.gmr)
}

// required uint64 timestamp = 3;
inline bool Transaction::has_timestamp() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Transaction::set_has_timestamp() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Transaction::clear_has_timestamp() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Transaction::clear_timestamp() {
  timestamp_ = GOOGLE_ULONGLONG(0);
  clear_has_timestamp();
}
inline ::google::protobuf::uint64 Transaction::timestamp() const {
  // @@protoc_insertion_point(field_get:cctx.Transaction.timestamp)
  return timestamp_;
}
inline void Transaction::set_timestamp(::google::protobuf::uint64 value) {
  set_has_timestamp();
  timestamp_ = value;
  // @@protoc_insertion_point(field_set:cctx.Transaction.timestamp)
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace cctx

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_tx_2eproto__INCLUDED
